## code to prepare `DATASET` dataset goes here

obama <-
  structure(list(word = c("thats", "world", "will", "america",
                          "people", "can", "work", "years", "make", "year", "american",
                          "just", "new", "americans", "change", "economy", "now", "every",
                          "want", "weve", "better", "even", "need", "see", "country", "future",
                          "get", "job", "like", "back", "security", "way", "keep", "know",
                          "one", "past", "right", "still", "time", "workers", "also", "jobs",
                          "next", "system", "doesnt", "isil", "leadership", "voices", "care",
                          "energy", "everything", "give", "going", "made", "power", "together",
                          "war", "big", "politics", "agree", "best", "cut", "democracy",
                          "economic", "families", "help", "many", "opportunity", "states",
                          "tonight", "well", "without", "cant", "dont", "americas", "basic",
                          "believe", "business", "come", "congress", "countries", "happen",
                          "health", "kids", "last", "may", "military", "national", "nearly",
                          "needs", "place", "political", "president", "progress", "seven",
                          "spirit", "take", "vote", "especially", "got", "lot", "love",
                          "matter", "planet", "start", "sure", "allies", "away", "businesses",
                          "climate", "comes", "communities", "day", "done", "education",
                          "elected", "everyone", "fellow", "first", "foreign", "government",
                          "hard", "history", "important", "international", "long", "look",
                          "money", "much", "nation", "oil", "pass", "pay", "safe", "save",
                          "science", "stand", "terrorists", "travel", "ways", "words",
                          "working", "almost", "answer", "approach", "around", "changes",
                          "everybody", "final", "harder", "hardworking", "ill", "less",
                          "makes", "retirement", "single", "student", "talk", "theres",
                          "things", "told", "wont", "agreement", "average", "benefits",
                          "build", "built", "century", "chamber", "citizens", "college",
                          "commitment", "community", "control", "cuts", "end", "equal",
                          "face", "fair", "fall", "fighting", "generations", "global",
                          "good", "great", "interests", "issues", "justice", "let", "life",
                          "live", "means", "medical", "middle", "might", "nations", "office",
                          "open", "others", "program", "protect", "put", "qaeda", "say",
                          "set", "show", "speaker", "state", "strength", "strong", "support",
                          "terrorist", "thing", "training", "troops", "two", "united",
                          "use", "young", "biggest", "citizen", "crisis", "didnt", "else",
                          "fact", "family", "feel", "focus", "getting", "hes", "incredible",
                          "isnt", "kind", "lead", "line", "play", "push", "quiet", "reason",
                          "reflect", "resources", "rights", "rules", "second", "serious",
                          "shouldnt", "strongest", "syria", "tougher", "1", "wants", "whats",
                          "achieve", "act", "affordable", "ago", "already", "another",
                          "areas", "argue", "ask", "attacks", "behind", "bipartisan", "brings",
                          "budget", "call", "challenges", "chance", "choice", "choices",
                          "civilians", "clean", "coal", "coalition", "collective", "companies",
                          "confidence", "congressional", "cost", "course", "coverage",
                          "decisions", "depends", "development", "doubt", "earth", "east",
                          "either", "enemies", "enough", "ever", "far", "favor", "fight",
                          "fighters", "find", "force", "forces", "freedom", "gives", "growing",
                          "helping", "higher", "hold", "improve", "instead", "insurance",
                          "interest", "iran", "iraq", "law", "leaders", "learn", "lets",
                          "lowincome", "mean", "million", "month", "must", "none", "pace",
                          "path", "percent", "possible", "poverty", "powerful", "promise",
                          "protecting", "providing", "public", "reach", "recognize", "record",
                          "reform", "research", "respect", "rest", "result", "saving",
                          "saw", "school", "send", "shape", "since", "something", "speak",
                          "spread", "started", "steps", "stop", "stopped", "stronger",
                          "students", "taken", "taking", "tax", "taxes", "technology",
                          "tens", "think", "today", "tools", "transition", "try", "trying",
                          "ukraine", "understand", "union", "vice", "violence", "wages",
                          "washington", "accelerate", "africa", "air", "alone", "always",
                          "anew", "asia", "assembly", "attention", "beat", "begins", "bills",
                          "bless", "broken", "brothers", "cancer", "careers", "commerce",
                          "computer", "conflicts", "constructive", "corporate", "created",
                          "cure", "decline", "depend", "different", "discovery", "diversity",
                          "early", "easier", "easy", "entrepreneur", "everywhere", "fear",
                          "fields", "finally", "folks", "god", "gone", "gotten", "handful",
                          "havent", "immigrant", "immigrants", "income", "innovation",
                          "intend", "internet", "iowa", "isolating", "ive", "lift", "lincoln",
                          "lose", "manufacturing", "muster", "networks", "online", "optimism",
                          "overnight", "parties", "parts", "party", "person", "plenty",
                          "plotting", "politicians", "pose", "priorities", "prison", "problem",
                          "promises", "pull", "pushing", "question", "real", "recruit",
                          "red", "relations", "respects", "retrain", "rigged", "rooted",
                          "sector", "shot", "sixty", "society", "soldier", "solve", "son",
                          "space", "stamp", "strengths", "ten", "theyve", "third", "threat",
                          "todays", "trends", "truth", "turning", "unarmed", "unconditional",
                          "unemployment", "unique", "voice", "voting", "vulnerable", "wage",
                          "walking", "wasnt", "whatever", "whether", "willingness", "word",
                          "worked", "works", "worst", "youll", "youre", "accounts", "across",
                          "acted", "actions", "address", "advance", "afford", "afghanistan",
                          "african", "ahead", "allow", "allowing", "anyone", "anywhere",
                          "approve", "assistance", "attack", "believed", "beyond", "bigger",
                          "bin", "bite", "blow", "body", "bonds", "bound", "brave", "breakthroughs",
                          "building", "carbon", "cause", "changed", "changing", "charge",
                          "child", "children", "china", "code", "colombia", "coming", "common",
                          "competition", "concern", "confident", "constitution", "continue",
                          "courage", "create", "creative", "critical", "cuba", "customers",
                          "danger", "dangerous", "deal", "debate", "debates", "debating",
                          "decade", "decades", "decency", "defend", "deficits", "deliver",
                          "delivered", "demand", "democrats", "deny", "determined", "developing",
                          "difficult", "discussion", "disease", "districts", "doctors",
                          "dollars", "dreams", "drug", "effort", "efforts", "eighth", "election",
                          "elections", "ensure", "environment", "epidemic", "evil", "expand",
                          "expanding", "extending", "extra", "failed", "failing", "faith",
                          "famine", "finest", "flow", "food", "founders", "four", "fourth",
                          "fuels", "fund", "funds", "gas", "generate", "generation", "girls",
                          "goal", "goals", "greater", "growth", "guarantee", "half", "hand",
                          "havens", "hemisphere", "high", "highs", "hit", "hivaids", "homeowners",
                          "hope", "hopeful", "human", "immigration", "including", "increased",
                          "individuals", "influence", "inspired", "intelligence", "investment",
                          "issue", "join", "keeping", "knows", "laden", "land", "lasting",
                          "later", "launched", "leader", "leading", "left", "letting",
                          "level", "liberty", "lines", "lives", "local", "lost", "loved",
                          "making", "markets", "math", "matters", "meaning", "measure",
                          "medicare", "meet", "members", "message", "millions", "mission",
                          "modernize", "movements", "nuclear", "number", "often", "opened",
                          "order", "osama", "package", "pakistan", "part", "partnering",
                          "patients", "paychecks", "peace", "peaceful", "period", "permanent",
                          "plan", "policy", "practices", "private", "products", "promising",
                          "promote", "proposals", "prosperity", "provide", "pursue", "raising",
                          "rate", "rebuild", "reduce", "reforms", "region", "regions",
                          "reject", "report", "republicans", "require", "requires", "results",
                          "ride", "rise", "rising", "rule", "run", "safer", "said", "savings",
                          "says", "scientific", "scientists", "secure", "seeing", "sell",
                          "senator", "share", "short", "six", "size", "slipping", "small",
                          "social", "solution", "soon", "sources", "standing", "stay",
                          "stays", "stood", "straight", "strategy", "strengthen", "strengthens",
                          "struggling", "supporting", "tape", "taxpayers", "teachers",
                          "thank", "thousands", "threaten", "top", "tough", "track", "trapped",
                          "treating", "treatments", "trucks", "trust", "turned", "undermine",
                          "uranium", "veterans", "vital", "welcome", "white", "whole",
                          "whose", "wise", "within", "worlds", "worry", "worth", "able",
                          "abuse", "accept", "accomplish", "action", "active", "actually",
                          "adhere", "aint", "allowed", "although", "amazing", "ambitious",
                          "announcing", "antsy", "anxious", "anybody", "anytime", "apartments",
                          "application", "appreciate", "arent", "arguments", "arizona",
                          "arming", "arsenal", "asian", "asking", "attitudes", "austin",
                          "authorize", "auto", "automated", "avoided", "avoids", "background",
                          "bad", "bankroll", "banks", "bargaining", "battling", "became",
                          "become", "becoming", "beijing", "belief", "benghazi", "betrays",
                          "biden", "bighearted", "black", "blood", "board", "boardrooms",
                          "bold", "bomb", "boosted", "born", "borrowers", "boss", "boston",
                          "bouncing", "brakes", "branches", "brand", "breaks", "bridged",
                          "briefing", "broaden", "broadly", "brochure", "bucks", "bullied",
                          "busy", "calls", "campaign", "camps", "capacity", "carpet", "carver",
                          "cast", "casts", "causes", "cell", "central", "charity", "cheaper",
                          "cheer", "childhood", "chinese", "citizenship", "civil", "claimed",
                          "claiming", "claims", "classes", "cleareyed", "clocked", "close",
                          "cold", "combined", "company", "compromise", "concentrated",
                          "conflict", "congressman", "connects", "consolidate", "contested",
                          "contracts", "contradicts", "controls", "conventional", "cooperation",
                          "cop", "corporations", "correctness", "costs", "count", "courts",
                          "creation", "credibility", "creed", "criminal", "cuban", "cures",
                          "cutting", "cynical", "cynics", "damage", "dares", "date", "decadeslong",
                          "demands", "depression", "deserve", "despite", "destroyed", "destroying",
                          "died", "diminished", "diminishes", "diplomacy", "diplomatic",
                          "direct", "dirtier", "dirty", "disagree", "disaster", "disciplined",
                          "dispute", "disrupt", "disruptions", "distributed", "divide",
                          "dna", "dogmas", "door", "drawing", "dreamer", "durable", "earlier",
                          "earnings", "ebola", "echoing", "edison", "eight", "eighteen",
                          "elderly", "element", "elevated", "embargo", "emerged", "empires",
                          "employerbased", "employs", "encourages", "ends", "enforce",
                          "engineering", "enormous", "entire", "entrenched", "environmentalists",
                          "envy", "ethic", "ethnic", "exactly", "example", "except", "existence",
                          "existing", "expectations", "expected", "expense", "expensive",
                          "extraordinary", "extreme", "eyes", "facts", "fairness", "falls",
                          "fanatics", "father", "fears", "feed", "feeding", "feels", "fiction",
                          "fifties", "fifty", "figured", "filling", "finance", "financial",
                          "financing", "finds", "finish", "five", "fix", "fixing", "focused",
                          "foremost", "forged", "forsake", "forties", "fortunately", "forty",
                          "fossil", "fought", "francis", "frontier", "frustration", "gain",
                          "gained", "gallon", "gaps", "garages", "gay", "george", "gets",
                          "gifts", "giving", "glory", "goodness", "goodpaying", "grace",
                          "graduates", "graduation", "grandkids", "grinds", "grit", "group",
                          "grows", "guantanamo", "guessing", "gun", "halt", "hands", "handson",
                          "hatred", "headwinds", "hear", "hedge", "helped", "helps", "hidden",
                          "hire", "holiness", "hopeless", "hopper", "hot", "hotter", "hubs",
                          "humor", "hunted", "idea", "ideology", "ignoring", "iii", "imitate",
                          "imperatives", "imports", "impose", "industry", "inequality",
                          "inevitable", "inflation", "influx", "inside", "insist", "instability",
                          "institutes", "insult", "invest", "inward", "isils", "jobready",
                          "joe", "johnson", "katherine", "kid", "kill", "killers", "kindness",
                          "king", "knowing", "largest", "late", "latin", "latino", "learned",
                          "leave", "led", "lesson", "lessons", "leverage", "lie", "lifeblood",
                          "lifted", "limit", "linked", "list", "listen", "living", "loan",
                          "locate", "lonely", "longer", "longest", "longterm", "looming",
                          "loses", "loss", "low", "loyalty", "majority", "malaria", "malice",
                          "manage", "marathon", "marks", "marry", "masses", "mat", "maybe",
                          "meant", "meanwhile", "memories", "millennia", "minds", "mine",
                          "minimum", "mobile", "mobilize", "moon", "moonshot", "moscow",
                          "mosque", "motivated", "murderers", "muslims", "namely", "narrow",
                          "nationbuild", "native", "necessary", "nextgeneration", "nucleararmed",
                          "nurse", "nurtured", "obligations", "occupying", "ocean", "offend",
                          "offering", "offshore", "ones", "openness", "opponents", "optimistic",
                          "orbit", "outdated", "outward", "overcame", "overrides", "overthetop",
                          "owner", "paid", "pandemic", "partiers", "partnership", "patient",
                          "paying", "payments", "pays", "peddling", "peril", "perpetrator",
                          "personalizing", "pick", "pickup", "places", "platform", "plots",
                          "point", "poison", "policeman", "polls", "pollution", "pope",
                          "positioned", "pouring", "practice", "pray", "precious", "prefer",
                          "prek", "prescription", "preserve", "presidency", "presidents",
                          "pretty", "prevent", "prevents", "principled", "priority", "privatesector",
                          "problems", "process", "produce", "profits", "profound", "project",
                          "prop", "propaganda", "protected", "protections", "protects",
                          "protester", "prove", "putting", "quagmire", "quarterly", "questions",
                          "quo", "race", "racing", "raise", "rallying", "rancor", "rates",
                          "rather", "rational", "reaching", "ready", "reality", "rebuilding",
                          "recession", "recipe", "recipients", "recklessness", "reclaiming",
                          "recovered", "recruitment", "reduced", "reflects", "reformed",
                          "refugees", "regardless", "regrets", "regulations", "reignite",
                          "reinvented", "religion", "religions", "rely", "remake", "remote",
                          "replace", "representative", "reshaping", "resolve", "respond",
                          "responsible", "restore", "restored", "retire", "retool", "returns",
                          "rhetoric", "rich", "role", "roll", "rolled", "rooftops", "roosevelt",
                          "ruin", "russia", "russians", "ryan", "sally", "sanctions", "scapegoat",
                          "scourge", "season", "secured", "seek", "selves", "served", "serves",
                          "setting", "shareholders", "shifts", "shipped", "shores", "shorter",
                          "shrink", "shut", "sick", "silicon", "simple", "sits", "sitting",
                          "slam", "slowed", "smarter", "solar", "solving", "somebody",
                          "someday", "someone", "somewhere", "souls", "sound", "spend",
                          "spilling", "spot", "sputnik", "squeezed", "stage", "stake",
                          "stamping", "standard", "starting", "startups", "status", "steadily",
                          "stockpile", "store", "story", "strain", "strategies", "streak",
                          "street", "stretch", "strikes", "stuck", "sturdy", "subsidize",
                          "superpower", "supports", "surprise", "surveys", "suspicion",
                          "sustainable", "systems", "tackling", "talked", "targets", "task",
                          "taught", "tea", "teacher", "teamed", "tell", "telling", "tends",
                          "territory", "texas", "theyre", "thomas", "thought", "threatened",
                          "threatening", "three", "threequarters", "thriving", "til", "took",
                          "tpp", "traditional", "transformation", "transpacific", "transportation",
                          "treasure", "tribes", "twelve", "twisted", "tyrants", "ultimately",
                          "unanswered", "understanding", "uniquely", "unnecessary", "unpatriotic",
                          "unraveling", "uphold", "upon", "urgent", "urging", "uses", "valley",
                          "value", "vandalized", "vicious", "victim", "vietnam", "villages",
                          "vision", "volunteers", "voters", "wait", "wall", "warmest",
                          "wars", "watching", "wave", "weak", "weaken", "weakens", "weaker",
                          "wealth", "wealthiest", "weapons", "weight", "west", "whove",
                          "widen", "willing", "wind", "winning", "withers", "woman", "worker",
                          "worse", "wright", "write", "wrong", "yemen", "yes", "york",
                          "youve", "abandon", "ability", "abroad", "acceptable", "accepts",
                          "access", "accessible", "accomplishments", "account", "accountability",
                          "achieved", "achievement", "achieving", "acknowledge", "acts",
                          "add", "added", "adding", "additional", "adjustment", "administration",
                          "admitted", "adult", "advanced", "advances", "advancing", "affect",
                          "afghan", "afghans", "africanamerican", "agencies", "agents",
                          "agreements", "agriculture", "aid", "aids", "aim", "aimed", "airmen",
                          "alarming", "alliance", "alltime", "along", "amid", "among",
                          "ample", "anbar", "angeles", "announce", "answered", "apart",
                          "apply", "appropriations", "approved", "approving", "april",
                          "armed", "armies", "army", "articles", "asked", "assassins",
                          "assisted", "association", "assured", "atlantic", "attacked",
                          "avenues", "avoid", "awakening", "backgrounds", "backing", "baghdad",
                          "balance", "ballistic", "bans", "barriers", "base", "based",
                          "battalions", "battery", "beacon", "began", "begin", "beginning",
                          "behavior", "belarus", "beloved", "bias", "bill", "billion",
                          "bloated", "bloodsoaked", "blown", "bob", "boehner", "bombs",
                          "border", "borders", "boundaries", "boys", "break", "breakthrough",
                          "breed", "brigade", "brigades", "brilliance", "bring", "bringing",
                          "brought", "brutality", "budgets", "burma", "buying", "called",
                          "calling", "came", "canada", "capability", "capital", "captured",
                          "capturing", "carry", "carrying", "cars", "caskets", "catch",
                          "cease", "celebrating", "cells", "challenge", "chaos", "charitable",
                          "checks", "cheney", "choose", "cities", "city", "civilian", "cleaner",
                          "clear", "clearing", "cloning", "coast", "combat", "commander",
                          "commanders", "commitments", "committed", "committee", "communications",
                          "compassion", "compassionate", "compete", "competitive", "competitiveness",
                          "complete", "complicated", "concentrate", "conditions", "confederation",
                          "confirmation", "confront", "confronting", "conscience", "consumer",
                          "consumption", "containing", "continues", "contrast", "convene",
                          "convention", "cooperate", "creating", "credit", "crippling",
                          "crops", "crossings", "cycle", "daily", "dangers", "dear", "deaths",
                          "debaathification", "decent", "declared", "declined", "dedicated",
                          "defeated", "defeating", "defines", "defining", "delay", "delayed",
                          "delegates", "democratic", "dependence", "deploying", "derail",
                          "described", "deserves", "desire", "desk", "despair", "despise",
                          "destinies", "destiny", "destruction", "determination", "determine",
                          "develop", "dictatorship", "differences", "dignity", "directly",
                          "directs", "disappearing", "discover", "discovered", "disintegration",
                          "displaced", "disrupted", "distance", "distinction", "distinguished",
                          "divisive", "doha", "dole", "donations", "donna", "doors", "double",
                          "doubled", "draft", "dramatic", "drastic", "drawdown", "driven",
                          "dropouts", "duty", "dutyfree", "dynamic", "earmark", "earmarks",
                          "earn", "edge", "effective", "effectively", "efficient", "eliminate",
                          "embodied", "embolden", "embryonic", "emerge", "emergency", "emissions",
                          "emissionsfree", "employer", "empower", "enact", "encouraging",
                          "ended", "ending", "endure", "enemy", "enforcement", "engaged",
                          "engineers", "enrich", "enrichment", "enter", "enthusiasm", "entitlement",
                          "entrepreneurs", "essential", "establish", "ethical", "evening",
                          "eventually", "executive", "expanded", "expect", "expeditionary",
                          "expire", "explaining", "explore", "exports", "extend", "extremism",
                          "extremists", "faced", "fail", "faithbased", "0", "fannie", "farmers",
                          "fast", "faster", "february", "federal", "fences", "field", "finances",
                          "finery", "fingers", "flexibility", "flowing", "fly", "follow",
                          "followed", "foreclosure", "forth", "forward", "found", "fragile",
                          "freddie", "free", "freedoms", "freer", "friday", "friend", "friends",
                          "front", "frontiers", "full", "fully", "funding", "futures",
                          "gains", "gases", "gave", "gavel", "general", "genius", "genocide",
                          "gentlemen", "georgia", "given", "goods", "gouverneur", "graders",
                          "grandchildren", "grants", "grassroots", "grateful", "gratitude",
                          "greatness", "greenhouse", "grew", "grim", "ground", "groups",
                          "grow", "guardsmen", "guests", "guide", "guided", "gulf", "hallowed",
                          "halls", "hamas", "happened", "happiness", "happy", "harm", "haven",
                          "havoc", "healing", "heart", "hearts", "held", "hezbollah", "highest",
                          "hiring", "hispanic", "holding", "holy", "home", "homeland",
                          "homeownership", "homes", "honors", "horrific", "hospitals",
                          "host", "hotel", "house", "housing", "humane", "humanitarian",
                          "humanity", "hundreds", "hunger", "ideals", "ideological", "ignore",
                          "illegal", "illegally", "images", "imagined", "implementing",
                          "impossible", "improved", "improvements", "incentives", "include",
                          "includes", "increase", "increases", "increasing", "increasingly",
                          "independence", "india", "information", "initial", "initiative",
                          "initiatives", "inkstained", "inner", "innovative", "inspire",
                          "instant", "intentions", "investing", "iranian", "irans", "iraqi",
                          "iraqis", "irs", "israel", "israelis", "items", "jerusalem",
                          "jets", "jordan", "jubilant", "judges", "judicial", "junk", "key",
                          "killed", "killings", "kitchen", "korea", "kurds", "lack", "ladies",
                          "laid", "landmark", "large", "launch", "launching", "lawful",
                          "laws", "lawsuits", "leads", "learning", "lebanon", "legislation",
                          "letter", "levels", "liability", "liberate", "lies", "lifelines",
                          "limb", "load", "london", "looking", "los", "losing", "mac",
                          "madam", "madrid", "mae", "maintain", "major", "malariarelated",
                          "march", "marine", "marines", "marked", "market", "massive",
                          "matched", "medicaid", "medicine", "member", "men", "met", "mexico",
                          "militia", "millennium", "minute", "miracle", "missiles", "moment",
                          "moments", "momentum", "monitor", "months", "moral", "morris",
                          "mortgages", "mosques", "mourners", "move", "moving", "nato",
                          "negotiations", "neighborhoods", "neighbors", "neither", "never",
                          "newfound", "night", "nights", "noble", "nominees", "nonpublic",
                          "north", "november", "numbers", "numerous", "oath", "objective",
                          "offense", "offer", "offered", "officers", "opening", "operations",
                          "operatives", "opportunities", "oppose", "opposed", "opposing",
                          "oppress", "oppression", "option", "options", "orders", "ordinary",
                          "organizations", "orleans", "overseas", "overwatch", "owe", "owes",
                          "pain", "painful", "palestine", "palestinian", "palestinians",
                          "panama", "parents", "parliament", "partner", "passage", "passed",
                          "passenger", "passing", "patenting", "patrol", "pell", "pelosi",
                          "pension", "peoples", "performing", "permanently", "persian",
                          "personally", "personnel", "peru", "petraeus", "phase", "philadelphia",
                          "philosophy", "physical", "pioneer", "plane", "planning", "plans",
                          "playing", "pleased", "pledge", "plot", "plunge", "pockets",
                          "police", "poor", "poorest", "popular", "populism", "posted",
                          "potential", "powers", "preamble", "preferences", "premise",
                          "preparing", "pressing", "pressure", "pressures", "prevailed",
                          "prey", "prices", "principle", "principles", "privacy", "profile",
                          "programs", "projects", "prompt", "proposal", "proposed", "prosper",
                          "prosperous", "protection", "protective", "proud", "provinces",
                          "provincial", "purchasing", "purpose", "pursuing", "pursuit",
                          "purveyors", "qaedairaq", "qaedas", "quality", "quarrel", "quickly",
                          "railed", "raised", "ramallah", "range", "reached", "reaches",
                          "reading", "reaffirm", "realize", "realized", "reauthorize",
                          "recently", "reclaim", "recognizes", "recommendations", "recommended",
                          "reconciliation", "reconstruction", "reduces", "reducing", "refinance",
                          "reflection", "refuse", "regaining", "regime", "rejoin", "release",
                          "released", "reliable", "relief", "remain", "remains", "reminder",
                          "renewable", "repeatedly", "replaced", "reports", "reprogram",
                          "republican", "researchers", "resentment", "resides", "resilience",
                          "resolved", "respecting", "responded", "responsibilities", "responsibility",
                          "return", "revenues", "reverse", "reviewed", "revision", "ripped",
                          "risked", "roads", "robust", "rose", "rostrum", "round", "rulers",
                          "sacrifice", "sadly", "sailors", "sanctuaries", "sanctuary",
                          "saying", "scholarships", "schools", "sciences", "scores", "searching",
                          "secret", "secretary", "sectarian", "seemed", "seems", "seen",
                          "selfgovernment", "selling", "senate", "sensible", "sent", "september",
                          "servants", "serve", "service", "services", "serving", "session",
                          "shalala", "shared", "sharing", "shia", "shifting", "showed",
                          "sidebyside", "sides", "signs", "similar", "site", "skill", "skilled",
                          "skills", "skin", "sleepless", "slow", "slower", "slowing", "snuck",
                          "sobered", "soil", "soldiers", "solemn", "source", "south", "special",
                          "spending", "spouses", "spreading", "stability", "staggering",
                          "staying", "steep", "stem", "stepped", "stirring", "strategic",
                          "streets", "strengthening", "strongholds", "struggle", "subject",
                          "submitted", "substantially", "succeed", "succeeding", "success",
                          "successes", "successful", "sudan", "sudden", "suit", "summit",
                          "sunni", "sunnis", "surge", "surges", "surplus", "suspend", "sustain",
                          "tables", "talented", "taliban", "talking", "talks", "tallest",
                          "tariffs", "taxfree", "team", "teams", "technologies", "tehran",
                          "temptation", "terminates", "territories", "terror", "tested",
                          "thanks", "threats", "throngs", "times", "tired", "toil", "tomorrow",
                          "totaling", "toward", "trade", "traditions", "traffickers", "train",
                          "trained", "trains", "transfer", "transformed", "transitioning",
                          "transparency", "treated", "treatment", "tribal", "troop", "troubled",
                          "truly", "trusting", "turbulent", "type", "tyranny", "uncertainty",
                          "undergoing", "undermined", "undersigned", "unethical", "unfairly",
                          "unfinished", "unfortunately", "unit", "unless", "unused", "upholds",
                          "upordown", "uprising", "usa", "used", "using", "valor", "verifiably",
                          "veto", "vigorous", "violent", "voluntarily", "volunteered",
                          "voted", "votes", "wagered", "warned", "warriors", "wasteful",
                          "watched", "weakened", "weapon", "weather", "wedding", "week",
                          "welfare", "wherever", "whim", "wisdom", "wisely", "witness",
                          "witnessed", "women", "worried", "worthy", "wounded", "wreaking",
                          "yet", "zimbabwe"), count = c(30, 24, 22, 21, 21, 20, 20, 18,
                                                        17, 17, 16, 16, 16, 15, 15, 15, 15, 14, 14, 14, 13, 13, 13, 13,
                                                        12, 12, 12, 11, 11, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8,
                                                        8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6,
                                                        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                                                        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                                                        5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                                                        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                                                        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3,
                                                        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                                                        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                                                        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                                                        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                                                        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                                                        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                                        0, 0, 0, 0, 0, 0, 0, 0)),
            .Names = c("word", "count"), class = c("spec_tbl_df", "tbl_df", "tbl", "data.frame"),
            row.names = c(NA, -2297L),
            spec = structure(list(cols = structure(list(word = structure(list(), class = c("collector_character","collector")),
                                                        count = structure(list(), class = c("collector_double","collector"))),
                                                   .Names = c("word", "count")),
                                  default = structure(list(), class = c("collector_guess","collector")), skip = 1),
                             .Names = c("cols", "default", "skip"), class = "col_spec"))


usethis::use_data(obama, overwrite = TRUE)
